Wip/9621 math only write with all params
ChimeraTK/DeviceAccess pull request #247
Opened 2022-04-04 15:18 UTC by killenb

The math plugin is only writing if all parameters and the accessor with the math plugin itself have been written once after the device has been opened. This prevents writing several invalid values because the formula has been used without having all data.

2022-04-05 08:58 UTC, mhier requested changes

2022-04-05 08:58 UTC, mhier commented on device_backends/LogicalNameMapping/src/LNMMathPlugin.cc
> +    auto backend = _backend.lock(); // get a shared pointer from the weak pointer
Please add a comment why no check is necessary that the lock is successful (you may drop the comment what this line does, as it is very obvious).

2022-04-05 08:58 UTC, mhier commented on device_backends/LogicalNameMapping/src/LNMMathPlugin.cc
> +    _skipWriteTransfer = true;
Maybe rename `_skipWriteTransfer` into `_skipWriteOperation` or `_skipWriteDelegation`? It does not only cause the transfer to be skipped but the entire write operation is not delegated to the `_target`.

2022-04-06 08:10 UTC, killenb commented on device_backends/LogicalNameMapping/include/LogicalNameMappingBackend.h
> +    // We cannot use atomic<VersionNumber> because then share_from_this is not working any more (something with not trivially copyable if I remember correctly)
I am using std::atomic<VersionNumber> now and got rid of the lock

2022-04-06 13:16 UTC, killenb commented
I also added the patch with boost::barrier scope to avoid yet another pull request plus review (although it's a feature creep for this pull request)

2022-04-06 13:48 UTC, mhier approved these changes

2022-04-07 11:59 UTC, merged