Wip/9551 force read only math plugin
ChimeraTK/DeviceAccess pull request #289
Opened 2022-11-10 10:35 UTC by d-rothe

please consider  wip/9439-lmapParseHexInt first since I based this branch on that

2022-11-10 11:16 UTC, mhier commented
This PR seems to be identical with  #288 - did something went wrong with the branches?

2022-11-10 13:14 UTC, d-rothe commented
> This PR seems to be identical with #288 - did something went wrong with the branches?
it's because I based this branch on wip/9439-lmapParseHexInt, please look at that pull request first. But work is actually unrelated.

2022-11-10 15:47 UTC, mhier commented
please rebase it on the master after #288 has been merged. I cannot really see what should be part of this PR otherwise... besides, the commit messages also don't really say much, please improve!

2022-11-11 15:43 UTC, d-rothe commented
> please rebase it on the master after #288 has been merged. I cannot really see what should be part of this PR otherwise... besides, the commit messages also don't really say much, please improve!

rebase was done

2022-11-14 08:28 UTC, mhier requested changes
Two minor formal changes only... Please keep in mind that the commit message (with the explanations from the comment) needs to be entered when squash merging (or alternatively squash the two commits first, edit the commit message and then merge without squashing into the master)

2022-11-14 09:28 UTC, d-rothe commented on tests/executables_src/testLMapForceReadOnlyPlugin.cc
> +   */
ok done

2022-11-14 09:33 UTC, mhier approved these changes

2022-11-14 16:50 UTC, merged