Re-Implement the UIO backend (#10601)
ChimeraTK/DeviceAccess pull request #294
Opened 2022-11-29 09:55 UTC by mc-randall

- Implemented register read/write access via UIO device driver.
- Implemented and tested handling of UIO interrupts.

2022-12-07 11:04 UTC, killenb requested changes

2022-12-07 11:23 UTC, killenb requested changes
The backend should overwrite the virtual barIndexValid() function so the logic_error is already thrown when creating the accessor, not only when the first read/write is happening.

2022-12-09 12:21 UTC, mc-randall commented on tests/unitTestsNotUnderCtest/testUioBackendWithHardware.cpp
> +  maximumAcceleration.read();
Changed test code accordingly.

2022-12-09 12:25 UTC, mc-randall commented on device_backends/uio/src/UioBackend.cc
> +    }
The unspecified use of adopt_lock on mutex has been removed.

2022-12-09 15:02 UTC, killenb approved these changes

2022-12-09 15:14 UTC, merged